data: # 数据路径
  train_path: artifacts/tokenized/tinystories_train.npy
  val_path: artifacts/tokenized/tinystories_valid.npy

model: # 模型超参数
  vocab_size:  10000
  context_length: 256
  num_layers: 4
  d_model: 512
  num_heads: 16
  d_ff: 1344
  rope_theta: 10000

optimizer: # 优化器超参数
  lr: 0001 # 默认lr，会被lr schedule覆盖掉
  betas: [0.9, 0.95]
  eps: 0.00000001
  weight_decay: 0.01

lr_schedule:
  alpha_max: 0.0001
  alpha_min: 0.00001
  warmup_iters: 100
  cosine_iters: 5000

training: # 训练时超参数
  device: cuda
  seed: 42
  max_iters: 5000
  batch_size: 32
  grad_clip: 1.0

logging:
  log_interval: 50
  eval_interval: 250
  eval_iters: 10
  log_path: artifacts/logs/tinystories_lr_1e-4.jsonl

checkpoint:
  resume_path:
  final_path: artifacts/checkpoints/tinystories_lr_1e-4_final.pt